[package]
name = "windows-sys-std"
version = "0.1.0"
edition = "2021"

[dependencies.windows-bindgen]
#version = "0.48.0"
git = 'https://github.com/microsoft/windows-rs.git'
branch = "standalone_std"
